name: ReceiptScanner
options:
  bundleIdPrefix: com.receiptscanner
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.1"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    GENERATE_INFOPLIST_FILE: YES
    DEVELOPMENT_TEAM: ""

targets:
  ReceiptScanner:
    type: application
    platform: iOS
    sources:
      - path: ReceiptScanner
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_KEY_CFBundleDisplayName: "Receipt Scanner"
        INFOPLIST_KEY_NSCameraUsageDescription: "This app needs camera access to scan receipts."
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        PRODUCT_BUNDLE_IDENTIFIER: com.receiptscanner.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        ENABLE_PREVIEWS: YES
    scheme:
      testTargets:
        - ReceiptScannerTests
        - ReceiptScannerUITests

  ReceiptScannerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ReceiptScannerTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: ReceiptScanner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.receiptscanner.tests
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"

  ReceiptScannerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ReceiptScannerUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: ReceiptScanner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.receiptscanner.uitests
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"

schemes:
  ReceiptScanner:
    build:
      targets:
        ReceiptScanner: all
        ReceiptScannerTests: [test]
        ReceiptScannerUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ReceiptScannerTests
        - ReceiptScannerUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
